### ISSUE TITLE
automatically copy the url to the clipboard after startup.

### ISSUE THREAD

**Issue by wChenonly** [rspack-contrib/rspack-plugins#11]
![image](https://github.com/rspack-contrib/rspack-plugins/assets/37658262/06fbb7ef-8c70-497e-82bb-0796aaaa89b1)

For hybrid development and debugging, it is very troublesome to manually copy the url of the terminal every time. I want to write a plug-in to automatically copy the url to the clipboard after startup. Can I put it in this repository?

**Comment by wChenonly** [comment]
> That's a great idea! How about create a separate repo in the `rspack-contrib` org? I can create the repo and add repo admin permissions to you.

LGTM!

**Comment by chenjiahan** [comment]
give me a repo name~

**Comment by chenjiahan** [comment]
`rspack-plugin-cli-copy` LGTM 😄

I have created the repo and sent invitation, please check:

https://github.com/rspack-contrib/rspack-plugin-cli-copy

![image](https://github.com/rspack-contrib/rspack-plugins/assets/7237365/a4577e85-24e9-435f-94ac-55fbadb700f1)

**Comment by wChenonly** [comment]
> `rspack-plugin-cli-copy` LGTM 😄
> 
> I have created the repo and sent invitation, please check:
> 
> [rspack-contrib/rspack-plugin-cli-copy](https://github.com/rspack-contrib/rspack-plugin-cli-copy)
> 
> ![image](https://private-user-images.githubusercontent.com/7237365/288767137-a4577e85-24e9-435f-94ac-55fbadb700f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTUyNTgsIm5iZiI6MTcwMTk1NDk1OCwicGF0aCI6Ii83MjM3MzY1LzI4ODc2NzEzNy1hNDU3N2U4NS0yNGU5LTQzNWYtOTRhYy01NWZiYWRiNzAwZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMTMxNTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzUwN2Q2NDVkOTI4MjI5YzIwOGEwY2Y1YzkxMDIxODJhMDY1YjUyMDU2NTkzYjdkZGQ3MTYzNzExZjEyMjE0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p45aI-zQi0ohIQRVnhsRA2_kQFDmI9n8zku3Y-CV3Tc)

thanks
